# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-27 09:40
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReleaseModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(unique=True)),
                ('Name', models.CharField(error_messages={'unique': 'Invalid release name - This name already exists in the DB.'}, max_length=20, unique=True)),
                ('ChangeList', models.CharField(max_length=200)),
                ('DjangoImage', models.FileField(storage=django.core.files.storage.FileSystemStorage(location='C:\\Users\\mzabaleta\\workspace\\diy4dot0\\src\\releases\\files'), upload_to='')),
                ('RaspImage', models.FileField(storage=django.core.files.storage.FileSystemStorage(location='C:\\Users\\mzabaleta\\workspace\\diy4dot0\\src\\releases\\files'), upload_to='')),
            ],
        ),
    ]
