# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-29 13:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('diy4dot0', '0002_delete_custom_perm'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalogItemModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DBTag', models.CharField(blank=True, editable=False, max_length=10, null=True)),
                ('HumanTag', models.CharField(max_length=10)),
                ('DataType', models.CharField(choices=[('INTEGER', 'Integer'), ('FLOAT', 'Float')], max_length=10)),
                ('Units', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='DigitalItemModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DBTag', models.CharField(blank=True, editable=False, max_length=10, null=True)),
                ('HumanTag', models.CharField(max_length=10)),
                ('Bit0', models.CharField(max_length=50)),
                ('Bit1', models.CharField(max_length=50)),
                ('Bit2', models.CharField(max_length=50)),
                ('Bit3', models.CharField(max_length=50)),
                ('Bit4', models.CharField(max_length=50)),
                ('Bit5', models.CharField(max_length=50)),
                ('Bit6', models.CharField(max_length=50)),
                ('Bit7', models.CharField(max_length=50)),
            ],
        ),
    ]
