BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBB

BBBB BBBBBBBBBBBBBBBBB

BBBBB BBBBBXXX XXBBBBBBBB

BBBBB BBBBBBBBBBBBXXXXXX XXX XXBBBBBBBB

BBBBB BBBB
  BBBBBB BBBB

  XXXX XXXXXXXXXXXXXXXXXXXXX
    XXX
      XXXXX XXXX XX XXXXXXXX XX XXXXXXBBB BBBBBBBBBBBBBBBBBXXXXXX XXXXXXX
    XXXX
  XXXXXX
BBBBBBBB BBBB

