BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBB

BBBB BBBBBBBBBBBBBBBBB

BBBBB BBBBBXXXXXXXX XXXXX XXXXBBBBBBBB

BBBBB BBBBBBBBBBBBXXXXXXXX XXXXX XXXXX XXXXBBBBBBBB

BBBBB BBBB
XXXX XXXXXXXXXXXXXXXXXXXXX
  XXX
    XXXXXX XXXXX XXXX XXXXX XXX XXXXX XXXX XXXXXXXX X XXXXXXXX XXXXX XXXX XXXX XXX
  XXXX
XXXXXX
BBBBBBBB BBBB

