BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBB

BBBB BBBBBBBBBBBBBBBBB

BBBBB BBBBBXXXX XXBBBBBBBB

BBBBB BBBBBBBBBBBBXXXXXXX XX XX XXXXBBBBBBBB

BBBBB BBBB
  BBBBBB BBBB

  XXXX XXXXXXXXXXXXXXXXXXXXX
    XXX
      XXXXXXX XXXXXX XXX XX XXXXXXBBB BBBBBBBBBBBBBBBBXXXXX XXXXXXX
    XXXX
  XXXXXX
BBBBBBBB BBBB

